# docker-compose.yml
version: '3'

services:

  serving:
    build:
      context: ./
      dockerfile: ./Dockerfile.serving
    image: ift6758/serving:latest
    ports:
      - "8000:8000"
    environment:
      WANDB_API_KEY: "${WANDB_API_KEY}"
      WANDB_ORG: "${WANDB_ORG}"

  streamlit:
    build:
      context: ./
      dockerfile: ./Dockerfile.streamlit
    image: ift6758/streamlit:latest
    ports:
      - "8501:8501"
    environment:
      GAME_CLIENT_HOST: "serving"
      GAME_CLIENT_PORT: "8000"
      SERVING_CLIENT_HOST: "serving"
      SERVING_CLIENT_PORT: "8000"
    depends_on:
      - serving
     
